### ISSUE TITLE
Define DB structure

### ISSUE THREAD

**Issue by garfieldua** [niddhogg/crm-stakeholder-university#13]
Define DB structure to match requirements

**Comment by garfieldua** [comment]
Table user

- user_id  
- password
- login
- first_name
- last_name
- role {“student”, “tutor”, “stakeholder”, “admin”}
- priority {from 0 to 5} // will be used for stakeholder by university


Table skill

- skill_id
- name


Table user_skill

- user_id
- skill_id


Table discipline

- discipline_id
- name


Table discipline_skill

- discipline_id
- skill_id
- 

Table user_discipline

- discipline_id
- tutor_id
- student_id
- passed {boolean} // will be used for student by tutor
- feedback_score // will be used by student and tutor  {0-5}

Table user_role

- user_role_id
- user_id
- role_name //role name

**Comment by lehinevych** [comment]
table user_discipline  was changed as follow:

Table course
course_id
discipline_id
tutor_id
student_id
passed {boolean} // will be used for student by tutor
feedback_score // will be used by student and tutor {0-5}
